# Athens main configuration file.
#
# See /usr/share/doc/athens/examples/config.dev.toml and https://docs.gomods.io
# for a full list of configuration properties and their documentation.


# Supported values are: 'development' and 'production'.
GoEnv = "production"

# Use go as Go binary.
# Although this property defaults to "go", Athens complains if it isn't specified explicitly.
GoBinary = "go"

# No pprof endpoints exposed.
EnablePprof = false

# Max 10 parallel "git clones" are allowed.
GoGetWorkers = 10

# Max 30 concurrent requests are allowed.
ProtocolWorkers = 30

# Use 300 seconds timeout for external network calls.
# Although this property defaults to 300, Athens complains if it isn't specified explicitly.
Timeout = 300

# Don't log "debug" and "trace" messages.
LogLevel = "info"


# Listen on localhost at port 3000.
Port = "127.0.0.1:3000"


# Modules direct access.
GoBinaryEnvVars = ["GOPROXY=direct"]

# Use separate download-mode hcl file.
DownloadMode = "file:/etc/athens/download-mode.hcl"


# Although this property defaults to "none", Athens complains if it isn't specified explicitly.
CloudRuntime = "none"


# Use google SumDB.
SumDBs = ["https://sum.golang.org"]

# Put your private modules here.
# e.g. NoSumPatterns = ["github.com/<your-name>/<your-private-repo>","<your-server>/<your-private-module>"]
NoSumPatterns = []


# No index used.
IndexType = "none"


# Use only one instance of Athens to manage concurrency.
SingleFlightType = "memory"


# Use disk storage backend.
StorageType = "disk"

[Storage]
	[Storage.Disk]
  	#	Use Athens cache directory to save modules.
		RootPath = "/var/cache/athens"
